CREATE TABLE settings (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    category_key VARCHAR(100) NOT NULL,
    category_label VARCHAR(150) NOT NULL,
    category_description VARCHAR(255),
    section_key VARCHAR(100) NOT NULL,
    section_label VARCHAR(150) NOT NULL,
    section_description VARCHAR(255),
    code VARCHAR(150) NOT NULL UNIQUE,
    label VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    value TEXT,
    value_type VARCHAR(30) NOT NULL,
    options_json TEXT,
    editable BOOLEAN NOT NULL DEFAULT TRUE,
    category_order INT NOT NULL DEFAULT 0,
    section_order INT NOT NULL DEFAULT 0,
    field_order INT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;

INSERT INTO settings (
    category_key, category_label, category_description,
    section_key, section_label, section_description,
    code, label, description, value, value_type, options_json, editable,
    category_order, section_order, field_order
) VALUES
('general', 'General Settings', 'Core application preferences and branding.',
 'general-preferences', 'General Preferences', 'Default behaviors and global contact details.',
 'general.site_name', 'Application Name', 'Name displayed throughout the interface.', 'RBAC Portal', 'STRING', NULL, TRUE,
 1, 1, 1),
('general', 'General Settings', 'Core application preferences and branding.',
 'general-preferences', 'General Preferences', 'Default behaviors and global contact details.',
 'general.support_email', 'Support Email', 'Primary email address for support communications.', 'support@demo.io', 'STRING', NULL, TRUE,
 1, 1, 2),
('general', 'General Settings', 'Core application preferences and branding.',
 'company-information', 'Company Information', 'Details that appear on customer-facing documents.',
 'company.name', 'Company Name', 'Legal or trading name used on correspondence.', 'Acme Corporation', 'STRING', NULL, TRUE,
 1, 2, 1),
('general', 'General Settings', 'Core application preferences and branding.',
 'company-information', 'Company Information', 'Details that appear on customer-facing documents.',
 'company.address', 'Headquarters Address', 'Primary company address used for billing.', '123 Market Street, Springfield, USA', 'TEXT', NULL, TRUE,
 1, 2, 2),
('general', 'General Settings', 'Core application preferences and branding.',
 'company-information', 'Company Information', 'Details that appear on customer-facing documents.',
 'company.phone', 'Support Phone', 'Main phone number for customer inquiries.', '+1-555-0110', 'STRING', NULL, TRUE,
 1, 2, 3),
('general', 'General Settings', 'Core application preferences and branding.',
 'localization', 'Localization', 'Regional defaults applied to invoices and proposals.',
 'localization.default_locale', 'Default Locale', 'Locale code used for formatting dates and numbers.', 'en-US', 'STRING', NULL, TRUE,
 1, 3, 1),
('general', 'General Settings', 'Core application preferences and branding.',
 'localization', 'Localization', 'Regional defaults applied to invoices and proposals.',
 'localization.timezone', 'Primary Time Zone', 'Time zone used for scheduling and reporting.', 'America/New_York', 'STRING', NULL, TRUE,
 1, 3, 2),
('general', 'General Settings', 'Core application preferences and branding.',
 'localization', 'Localization', 'Regional defaults applied to invoices and proposals.',
 'localization.currency', 'Default Currency', 'Currency code applied to finance modules.', 'USD', 'STRING', NULL, TRUE,
 1, 3, 3),
('general', 'General Settings', 'Core application preferences and branding.',
 'email-configuration', 'Email Configuration', 'Mail server settings for outbound notifications.',
 'email.sender', 'Sender Address', 'Email displayed as the sender on notifications.', 'no-reply@demo.io', 'STRING', NULL, TRUE,
 1, 4, 1),
('general', 'General Settings', 'Core application preferences and branding.',
 'email-configuration', 'Email Configuration', 'Mail server settings for outbound notifications.',
 'email.smtp_host', 'SMTP Host', 'Server hostname used to relay emails.', 'smtp.demo.io', 'STRING', NULL, TRUE,
 1, 4, 2),
('general', 'General Settings', 'Core application preferences and branding.',
 'email-configuration', 'Email Configuration', 'Mail server settings for outbound notifications.',
 'email.smtp_port', 'SMTP Port', 'Port number for the SMTP service.', '587', 'NUMBER', NULL, TRUE,
 1, 4, 3),
('general', 'General Settings', 'Core application preferences and branding.',
 'email-configuration', 'Email Configuration', 'Mail server settings for outbound notifications.',
 'email.use_tls', 'Use TLS', 'Whether TLS encryption is enforced for SMTP connections.', 'true', 'BOOLEAN', NULL, TRUE,
 1, 4, 4),
('general', 'General Settings', 'Core application preferences and branding.',
 'appearance', 'Appearance Settings', 'Customize the look and feel of the dashboard.',
 'appearance.primary_color', 'Primary Brand Color', 'Accent color applied to buttons, icons, and highlights.', '#2563EB', 'COLOR', NULL, TRUE,
 1, 5, 1),
('general', 'General Settings', 'Core application preferences and branding.',
 'system-update', 'System Update', 'Controls for release cadence and maintenance windows.',
 'system.auto_updates', 'Enable Automatic Updates', 'Automatically apply minor updates during maintenance windows.', 'false', 'BOOLEAN', NULL, TRUE,
 1, 6, 1),
('general', 'General Settings', 'Core application preferences and branding.',
 'system-update', 'System Update', 'Controls for release cadence and maintenance windows.',
 'system.maintenance_window', 'Maintenance Window', 'Preferred window for scheduled maintenance work.', 'Sundays 02:00-04:00 ET', 'STRING', NULL, TRUE,
 1, 6, 2),
('general', 'General Settings', 'Core application preferences and branding.',
 'system-information', 'System Information', 'Read-only metadata about the current deployment.',
 'system.version', 'Application Version', 'Current deployed software version.', '1.0.0', 'STRING', NULL, FALSE,
 1, 7, 1),
('general', 'General Settings', 'Core application preferences and branding.',
 'system-information', 'System Information', 'Read-only metadata about the current deployment.',
 'system.build', 'Build Reference', 'Internal build identifier for support teams.', '2024.10', 'STRING', NULL, FALSE,
 1, 7, 2),
('finance', 'Finance Settings', 'Billing, invoicing, and revenue configuration.',
 'finance-general', 'General Finance Settings', 'Default fiscal parameters.',
 'finance.base_currency', 'Base Currency', 'Primary currency used for accounting.', 'USD', 'STRING', NULL, TRUE,
 2, 1, 1),
('finance', 'Finance Settings', 'Billing, invoicing, and revenue configuration.',
 'finance-general', 'General Finance Settings', 'Default fiscal parameters.',
 'finance.fiscal_year_start', 'Fiscal Year Start', 'Month and day that mark the beginning of the fiscal year.', 'January 1', 'STRING', NULL, TRUE,
 2, 1, 2),
('finance', 'Finance Settings', 'Billing, invoicing, and revenue configuration.',
 'invoices-configuration', 'Invoices Configuration', 'Customize numbering and workflow defaults.',
 'invoices.prefix', 'Invoice Prefix', 'Text applied to the start of generated invoice numbers.', 'INV', 'STRING', NULL, TRUE,
 2, 2, 1),
('finance', 'Finance Settings', 'Billing, invoicing, and revenue configuration.',
 'invoices-configuration', 'Invoices Configuration', 'Customize numbering and workflow defaults.',
 'invoices.due_days', 'Default Due Days', 'Number of days after issue before invoices are due.', '30', 'NUMBER', NULL, TRUE,
 2, 2, 2),
('finance', 'Finance Settings', 'Billing, invoicing, and revenue configuration.',
 'invoices-configuration', 'Invoices Configuration', 'Customize numbering and workflow defaults.',
 'invoices.auto_send', 'Auto-send Invoices', 'Send invoices automatically on the issue date.', 'true', 'BOOLEAN', NULL, TRUE,
 2, 2, 3),
('finance', 'Finance Settings', 'Billing, invoicing, and revenue configuration.',
 'proposal-management', 'Proposal Management', 'Defaults for proposal creation and follow-up.',
 'proposals.prefix', 'Proposal Prefix', 'Text applied to generated proposal numbers.', 'PROP', 'STRING', NULL, TRUE,
 2, 3, 1),
('finance', 'Finance Settings', 'Billing, invoicing, and revenue configuration.',
 'proposal-management', 'Proposal Management', 'Defaults for proposal creation and follow-up.',
 'proposals.expiry_days', 'Default Expiry Days', 'Days until a proposal automatically expires.', '14', 'NUMBER', NULL, TRUE,
 2, 3, 2),
('finance', 'Finance Settings', 'Billing, invoicing, and revenue configuration.',
 'proposal-management', 'Proposal Management', 'Defaults for proposal creation and follow-up.',
 'proposals.reminders_enabled', 'Send Reminder Emails', 'Whether automatic reminders are sent before expiry.', 'true', 'BOOLEAN', NULL, TRUE,
 2, 3, 3),
('integrations', 'Integration Settings', 'Connect the platform to external services.',
 'google', 'Google Integration', 'OAuth credentials for Google Workspace features.',
 'integrations.google.client_id', 'Client ID', 'OAuth client identifier for Google integrations.', '', 'STRING', NULL, TRUE,
 3, 1, 1),
('integrations', 'Integration Settings', 'Connect the platform to external services.',
 'google', 'Google Integration', 'OAuth credentials for Google Workspace features.',
 'integrations.google.client_secret', 'Client Secret', 'OAuth client secret for Google integrations.', '', 'STRING', NULL, TRUE,
 3, 1, 2),
('integrations', 'Integration Settings', 'Connect the platform to external services.',
 'pusher', 'Pusher.com Integration', 'Realtime notifications and websocket connectivity.',
 'integrations.pusher.app_id', 'Pusher App ID', 'Unique application identifier from Pusher.', '', 'STRING', NULL, TRUE,
 3, 2, 1),
('integrations', 'Integration Settings', 'Connect the platform to external services.',
 'pusher', 'Pusher.com Integration', 'Realtime notifications and websocket connectivity.',
 'integrations.pusher.key', 'Pusher Key', 'Public API key used by clients.', '', 'STRING', NULL, TRUE,
 3, 2, 2),
('integrations', 'Integration Settings', 'Connect the platform to external services.',
 'pusher', 'Pusher.com Integration', 'Realtime notifications and websocket connectivity.',
 'integrations.pusher.secret', 'Pusher Secret', 'Secret token used for server authentication.', '', 'STRING', NULL, TRUE,
 3, 2, 3),
('integrations', 'Integration Settings', 'Connect the platform to external services.',
 'third-party', 'Other Third-Party Integrations', 'Webhook endpoints and API keys for additional services.',
 'integrations.slack.webhook_url', 'Slack Webhook URL', 'Incoming webhook used to post alerts to Slack.', '', 'STRING', NULL, TRUE,
 3, 3, 1),
('integrations', 'Integration Settings', 'Connect the platform to external services.',
 'third-party', 'Other Third-Party Integrations', 'Webhook endpoints and API keys for additional services.',
 'integrations.zapier.webhook_url', 'Zapier Webhook URL', 'Webhook invoked when workflow automations run.', '', 'STRING', NULL, TRUE,
 3, 3, 2),
('misc', 'Miscellaneous Settings', 'Additional options that do not fit other categories.',
 'miscellaneous', 'Miscellaneous Preferences', 'Feature toggles and operational controls.',
 'misc.beta_program', 'Enable Beta Features', 'Allow selected users to access beta functionality.', 'false', 'BOOLEAN', NULL, TRUE,
 4, 1, 1),
('misc', 'Miscellaneous Settings', 'Additional options that do not fit other categories.',
 'miscellaneous', 'Miscellaneous Preferences', 'Feature toggles and operational controls.',
 'misc.maintenance_mode', 'Maintenance Mode', 'Temporarily restrict access to administrators only.', 'false', 'BOOLEAN', NULL, TRUE,
 4, 1, 2),
('misc', 'Miscellaneous Settings', 'Additional options that do not fit other categories.',
 'miscellaneous', 'Miscellaneous Preferences', 'Feature toggles and operational controls.',
 'misc.admin_notes', 'Administrator Notes', 'Internal notes for operators and auditors.', 'Internal SOPs are stored in Confluence.', 'TEXT', NULL, TRUE,
 4, 1, 3);

INSERT IGNORE INTO permissions (code, name) VALUES
 ('SETTINGS_VIEW', 'View Settings'),
 ('SETTINGS_UPDATE', 'Update Settings');

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN ('SETTINGS_VIEW', 'SETTINGS_UPDATE')
WHERE r.code = 'SUPER_ADMIN';
