spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac_dashboard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: V1RY9m0xL8U7Q2pX5s6d8f1g2h3j4k5l6m7n8o9p0q1r2s3t4u5v6w7x8y9z0a
    access-token-ttl-seconds: 900
    refresh-token-ttl-seconds: 604800
  cors:
    allowed-origins:
      - http://localhost:*
      - http://127.0.0.1:*
      - http://0.0.0.0:*
  urls:
    login: http://localhost:3000/login
    verification: http://localhost:8080/api/v1/auth/verify
  brand:
    public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}
  category:
    public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}
  badge:
    public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}
  badge-category:
    public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
